version: "2"

services:
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
    environment:
    - GRID_MAX_SESSION=20
    - TIMEOUT=1200000
    - GRID_TIMEOUT=0
    - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
    logging:
      driver: awslogs
      options:
        awslogs-group: selenium-hub
        awslogs-region: eu-west-1
    mem_reservation: 1073741824
    mem_limit: 1073741824
    cpu_shares: 1023

  firefox-1:
    image: selenium/node-firefox:latest
    links:
    - hub:hub
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
    - NODE_MAX_SESSION=10
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    logging:
      driver: awslogs
      options:
        awslogs-group: selenium-nodes
        awslogs-region: eu-west-1
    mem_reservation: 3786407936
    mem_limit: 3786407936
    cpu_shares: 1791
    privileged: true  

  firefox-2:
    image: selenium/node-firefox:latest
    links:
    - hub:hub
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
    - NODE_MAX_SESSION=10
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    logging:
      driver: awslogs
      options:
        awslogs-group: selenium-nodes
        awslogs-region: eu-west-1
    mem_reservation: 3786407936
    mem_limit: 3786407936
    cpu_shares: 1791
    privileged: true
    networks:
    - selenium-grid

  chrome-1:
    image: selenium/node-chrome:latest
    links:
    - hub:hub
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
    - NODE_MAX_SESSION=10
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    logging:
      driver: awslogs
      options:
        awslogs-group: selenium-nodes
        awslogs-region: eu-west-1
    mem_reservation: 3786407936
    mem_limit: 3786407936
    cpu_shares: 1791
    privileged: true
    networks:
    - selenium-grid

  chrome-2:
    image: selenium/node-chrome:latest
    links:
    - hub:hub
    volumes:
    - /dev/shm:/dev/shm # Mitigates the Chromium issue described at https://code.google.com/p/chromium/issues/detail?id=519952
    environment:
    - NODE_MAX_SESSION=10
    - NODE_MAX_INSTANCES=10
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
    logging:
      driver: awslogs
      options:
        awslogs-group: selenium-nodes
        awslogs-region: eu-west-1
    mem_reservation: 3786407936
    mem_limit: 3786407936
    cpu_shares: 1791
    privileged: true
    networks:
    - selenium-grid
